gbdev/awesome-gbdev

scripts/urls-http-status
This script makes it a little easier to find dead links in the list. It's run like this:
```
$ ./scripts/urls-http-status 
```
and outputs a list of all URLs and their HTTP status code:
```
200 https://github.com/bwhitman/pushpin/blob/master/src/gbsound.txt
404 http://marc.rawer.de/gameboy/Docs/GBProject.pdf
200 https://github.com/BonsaiDen/gbasm
[...]
```
Sorting the output makes it easier to find those 404s:
```
$ ./scripts/urls-http-status | sort
```
=> Add script to check HTTP status for URLs.

README.md
The video is no longer available on Youtube. Instead link to the video portal of the conference where the talk was held.
=> Replace dead video link

README.md
Replaced the "Game Boy Programming Manual" broken link http://www.romhacking.net/documents/544/ with an alternative version http://www.chrisantonellis.com/files/gameboy/gb-programming-manual.pdf
=> Replaced Game Boy Programming Manual broken link

README.md
[pashutk/flappybird-gameboy](https://github.com/pashutk/flappybird-gameboy) – yet another gbdk flappybird clone written in C
=> Add pashutk/flappybird-gameboy

README.md
This repo is outdated; rgbgfx is now integrated with rgbds and ships as part of it.
=> Remove rgbgfx from list

README.md
Correct "Gameboy" and "GameBoy" to "Game Boy" in descriptions.
As discussed in #34, do not correct titles, as opposed to how I did in #33.
See also 573b31c and #8.
=> Make spelling of "Game Boy" consistent

README.md
The placement of this has been a difficult choice for me, so here's a summary of the discussion that occurred on Discord :
- The point of this is to be read before choosing a dev environment.
- It would make sense to put it in the Software Tutorials section, partly because of the section about programming tips.
- However, if put there (probably at the root), the user would probably already have chosen their dev environment, and would either have clicked the appropriate section directly, or skipped the entry altogether. This would make it useless.
- Another solution would have been to put it as the first entry of both the ASM and C sections ; but this doesn't solve the skipping issue mentioned above, and it creates a bad precedent : a duplicated entry.
- Placing the entry in the "Intro" …
=> Add "To C Or Not To C" writeup

README.md
Clang doesn't work without LLVM, having it separate seems to be confusing, and it's not like Clang works but LLVM doesn't, so it's best to have them together in Experimentals.
=> Move clang-gbz80 to Experimentals

README.md
An Emacs major-mode (syntax highlighter and related boilerplate) for editing RGBDS assembly source.
=> Add rgbds-mode

README.md
Adding lmmendes/game-boy-opcodes to Cheatsheets, Tables section.
It's basically a JSON representation of the http://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html for ease of parsing.
The file also includes some opcode length and timing fixes for known issues with the pastraiser.com original content.
=> Add lmmendes/game-boy-opcodes to Cheatsheets, Tables section

README.md
This tutorial is filled with bad practice, and as such is not awesome.
The section in which it's placed was wrong, too.
=> Remove OAM DMA tutorial

EMULATORS.md
Please add my own GBC emulator into EMULATORS.md.
[Worldwide](https://github.com/Akatsuki-py/Worldwide)
APU was ported from GoBoy, but the rest is a completely original, high-performance GBC emulator.
=> EMULATORS.md: add Worldwide

README.md
I found this page which gives some insight into the development process of swotGB, a javascript Game Boy emulator. 
I thought it might be a good addition to awesome gbdev, as it provides nice details about the development process, some of its intricacies as well as the fun that comes with it.
=> Add swotGB notes page to the emulator development section

README.md
Added GingerBread and the book _Game Boy Assembly Programming for the Modern Game Developer_ (both made by me). I added a new section for "Software libraries" as GingerBread didn't really fit "Sources" or "Boilerplates" in my opinion. If you/someone feels GingerBread should belong to some other category, feel free to change it (or let me know).
=> Adding GingerBread and Game Boy Assembly Programming for the Modern Game Developer

README.md
More complete, more up-to-date, and offers more functionality
=> Supersede rgbds-textmate with sublime-rgbds

README.md
See TheFakeMateo/rpp-backup#13
Besides, it's not a disassembly, but a ROM hack, so it was mis-classified anyway.
=> Remove RedPlusPlus

README.md
Since TRSE bundle its own compiler for its Pascal-like programming language it could also fit under "Compilers".
=> Add TRSE under "Development tools"

README.md
Due to the official **Gambatte** repository going private, I've added a link to the mirror of it on *The Game Boy Archive project.* I've decided to leave the original link, as after all, it is the official location of the project.
=> Added link to gb-archive backup mirror of Gambatte

README.md
Hi,
@rgalland and I, we independently simulated the living hell out of the schematics in [DMG-CPU-Inside](https://github.com/furrtek/DMG-CPU-Inside), hopefully catching all the bugs.
These are our simulations:
* https://github.com/rgalland/dmg_gb_ppu_simulation
* https://github.com/msinger/dmg-sim
We reported a lot of issues, but I think @furrtek is very busy de-capping some other chips, so we decided to remake the schematics in KiCad. :)
I removed the dash (-) between "CPU" and "B" in the other line, because the label on the chip always reads "DMG-CPU B", not "DMG-CPU-B". I thought since you take good care of spelling "Game Boy" the correct way, this should be corrected too.
We think our schematics are now mostly correct. There are still some swapped inputs of AND- and OR-gates, which …
=> Add link to fixed KiCad version of DMG-CPU B chip schematics

README.md
https://github.com/robert/gameboy-doctor
Moved over from https://github.com/gbdev/gbdev.github.io/pull/65 !
cc @avivace
=> Add Game Boy Doctor

README.md
This is a super-simple script I made the other day that can be used with Emulicious to generate statistics on which instructions get run the most by the CPU. TBH I'm not sure if it's really awesome enough for the list, since it's so basic and not really well-written at all. I guess I'll let the people here be the judge of that, but hopefully I at least set up the fork and PR properly.
=> Added opcode_count to Development Tools Section

MORE.md
Add the new sm83 assembler and compiler that were recently released.
=> MORE.md: Add Asm83 and Cate83 toolchain entries

README.md
[Rust-GB](https://github.com/zlfn/rust-gb) is a project that enables the development of GB ROM with Rust.
I think it has enough originality to be listed as an experimental compiler in this Awesome repository.
+) What is needed to add this project to the 'Compiler' (not the Experimental) section?
=> Add Rust-GB
