gbdev/awesome-gbdev

- README.md
Corrected a few missing full stops, spelling errors and formatting issues. Most importantly gave 'Pokémon' the correct 'é'.
> Various Awesome list text fixes

- README.md
Added new GBDK tutorial to the list of programming tutorials.
> Added GBDK Tutorial under programming tutorials section

- README.md
bentley/rgbds repository has been renamed to rednex/rgbds.
> Update address of RGBDS

- README.md
I found this useful when developing my emulator.
> Add documentation about pixel format

- README.md
Added an Atari 2600 Boxing clone for the Game Boy (Color)
> Add new C game (GBC Atari Boxing)

- README.md
> Fix wiz link

- README.md
Also clarify that previous item is a blog
> Add LADX Disassembly

- README.md
Not really a game, but neither is GB303, so 🤷‍♂️
> Add GBSlides

- README.md
Make line endings consistent with Contribution Guidelines.
Also make sure each entry is on one single line.
> Fix so all lines end with a period

- README.md
I'm actually not sure where to put this. I do feel it belongs under "Software Development", but is "Tools" the right category? Or should it have its own barren category? Is it a "Programming Tutorial" first and foremost? "Related sites, posts and projects" seems to not give this project enough credit.
Categorization suggestions welcome.
> Add Dot Matrix Game Editor

- README.md
Tutorial on Super Game Boy features
> Add Super Game Boy tutorial

- README.md
"Additions should be added to the bottom of the category" but it makes more sense to group syntax files together, right ?
> Redirect Pan Docs and add Npp syntax file

- README.md
> Add mGBA, a GBA emulator that also runs GB/GBC games

- README.md
> Add Atom syntax highlighting for RGBASM

- README.md
> Add Tobu Tobu Girl

- README.md
Isn't finished (what is?), but I think it looks very neat.
> Add mmlgb, an MML parser and GBDK driver

- README.md
Consistency in the list and with the official documentation
> Capitalize "rgbds"

- README.md
This is version 1.1 of the Game Boy manual with revised information and higher quality figures.
> Update link to latest version of manual.

- README.md
* Add the link to the talk on YouTube
* Add link to errata page
> Gekkio disobey talk

- README.md
I wasn't sure how to link the two parts, but I think this maybe works?
> Add part 2 of Sheep It Up! postmortem

- README.md
Fixes #87. Let me know if I should word it differently.
> Add notice to Ben Heck video

- articles/to_c_or_not_to_c.md
According to Discord's log, it's been a month now. I'm not late, am I?
> Copy "To C Or Not To C" writeup

- README.md
Add my own tutorial to the list.
This tutorial isn't finished yet, but I am actively developing it, and am aiming towards making it a complete tutorial to the whole GB. I believe it's currently on a similar lever to other tutorials available on the list, but I'm aiming to make it more complete, and thus I'd like to have feedback from it, at least from people reading this, and if possible from readers also.
Discuss.
> Add gb-asm-tutorial

- README.md
Doesn't quite qualify as a game, so I added it to the demos section.
> Add matrix-rain-gb to demos

- README.md
Added a new C Game and link to series of youtube tutorials, both created by me
> Added two new links for C

- README.md
Just thought I would throw in my own Dino clone written in GBDK! We can make dino the new flappy bird! :laughing:
The gif in the repository looks worse than it actually is, I'll update it soon. Check it out, if you'd like!
> Add another Dino clone to C links

- README.md
I am working on a port of Evoland (just first level) on GameBoy. As I published source code en Github, I think it can be an useful resource for developers :)
(to try the game online, you can go there → https://evogb.flozz.org/)
> Adds Evoland.gb to the C Homebrews

- README.md
Here are a couple tools I've posted this year that came out of developing a game for the DMG. Let me know if anything needs to change, if they don't qualify, or if the pull request should be submitted differently. (first time doing a pull request)
> Add Tools Tilemap GB and Tilemap Helper

- README.md
I think this project qualifies as awesome.
> Add DMG-CPU-Inside by furrtek

- README.md
Hi all,
I'm just started reading all the materials around the Game Boy and seems that more often than not the originals keep disappearing.
I'm not sure if you normally point to to a different place, hopefully we can keep track of this one.
Thank you
> Update 8-Bit Wonderland link to Archive

- README.md
The link wasn't working, I found a working version on another domain. Here's my fix.
> Fix peterwynroberts.com link

- README.md
> Add gb-vwf library

- README.md
Also fix the links to rgbds to point to the new location.
> Add rgbds-live and superfamiconv

- README.md
> Supersede Tetris disassembly with a more detailed one

- README.md
Added my sound effect driver under the music drivers and trackers section, not sure if it falls 100% under that category but it's close enough
> Added CBT-FX

- README.md
The disassembly is in the state where many main datastructures are documented, and it is mostly shiftable.
> Add my final fantasy adventure disassembly.

- EMULATORS.md
Adding [Boytacean](https://github.com/joamag/boytacean) to the list.
> Update EMULATORS.md - Adding Boytacean

- README.md
updating old "larolds jubilant junkyard" text and links to be "larolds retro gameyard"
adding Gumpy Function's platformer tutorial.
> updating larold's jubilant junkyard links. adding gumpy function tutorial.

- README.md
Disassembly of 'The Jungle Book' including utilities to extract assets.
> Adding 'The Jungle Book' disassembly.
